################################# Default configuration ###################
baseURL = "http://example.org/"
title = "徳島交響楽団"
theme = "airspace-hugo"
#themesDir = "../.."
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["en"]
DefaultContentLanguage = "ja"
DefaultContentLanguageInSubdir = false

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
page = "/"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
page = "/"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
page = "/"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
page = "/"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
page = "contact/"
attributes = ""

[[params.plugins.js]]
link = "plugins/iframe-auto-height/iframe-auto-height.js"
page = "/"
attributes = ""

############################### widgets #################################

[params.newsWidgets]
sidebar = ["recent_news", "news_category"]

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "150px"
# Meta data
description = "徳島交響楽団のウェブサイトです。"
author = "徳島交響楽団"
# Contact Information
phone = "088-665-6678"
fax = "088-637-1276"
email = "front@tso.serio.jp"
location = "〒771-0117 徳島市川内町鶴島277-23 音楽喫茶みき内 徳島交響楽団事務局"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false
customCSS = ["/css/custom.css"]

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

[Languages]
    ################################ Japanese Language ########################
    [Languages.ja]
    languageName = "日本語"
    languageCode = "ja"
    contentDir = "content/japanese"
    weight = 1
    # copyright
    copyright = "Copyright &copy; 2003 - {year} Tokushima Symphony Orchestra All Rights Reserved."


        ######################### japanese navigation #############################
        # main menu
        [[Languages.ja.menu.main]]
        name = "Home"
        URL = "/"
        weight = 1

        [[Languages.ja.menu.main]]
        name = "楽団紹介"
        URL = "about"
        weight = 2

        [[Languages.ja.menu.main]]
        name = "演奏会の記録"
        URL = "history"
        weight = 3

        [[Languages.ja.menu.main]]
        name = "ニュース"
        URL = "news"
        weight = 4

        [[Languages.ja.menu.main]]
        name = "団員募集"
        URL = "join"
        weight = 5

        [[Languages.ja.menu.main]]
        name = "お問い合わせ"
        URL = "/contact"
        weight = 6

        [[Languages.ja.menu.main]]
        name = "ジュニア"
        URL = "http://tso.serio.jp/junior/index.html"
        weight = 6

        [[Languages.ja.menu.main]]
        weight = 7
        name = "団員専用"
        hasChildren = true

        [[Languages.ja.menu.main]]
        parent = "団員専用"
        weight = 1
        name = "練習計画"
        URL = "practice"

        [[Languages.ja.menu.main]]
        parent = "団員専用"
        weight = 2
        name = "掲示板"
        URL = "http://tso.serio.jp/mem/imgboard.cgi"

        # footer menu
        [[Languages.ja.menu.footer]]
        name = "Home"
        URL = "/"
        weight = 1

        [[Languages.ja.menu.footer]]
        name = "楽団紹介"
        URL = "about"
        weight = 2

        [[Languages.ja.menu.footer]]
        name = "演奏会の記録"
        URL = "history"
        weight = 3

        [[Languages.ja.menu.footer]]
        name = "ニュース"
        URL = "news"
        weight = 4

        [[Languages.ja.menu.footer]]
        name = "団員募集"
        URL = "join"
        weight = 5

        [[Languages.ja.menu.footer]]
        name = "お問い合わせ"
        URL = "/contact"
        weight = 6

    ################################ English Language ########################
    [Languages.en]
    languageName = "English"
    languageCode = "en-us"
    contentDir = "content/english"
    weight = 2
    # copyright
    copyright = "Copyright &copy; 2003 - {year} Tokushima Symphony Orchestra All Rights Reserved."

        ######################### english navigation #############################
        # main menu
#        [[Languages.en.menu.main]]
#        name = "Home"
#        URL = "/"
#        weight = 1
#
#        [[Languages.en.menu.main]]
#        name = "About"
#        weight = 2
#
#        [[Languages.en.menu.main]]
#        name = "News"
#        URL = "news"
#        weight = 3
#
#        [[Languages.en.menu.main]]
#        name = "Contact"
#        URL = "contact"
#        weight = 4
#
#        # footer menu
#        [[Languages.en.menu.footer]]
#        name = "Contact"
#        URL = "contact"
#        weight = 6
